name: owl-mobile-native-mobile
options:
  bundleIdPrefix: app.wizardry.generated
targets:
  owl-mobile:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Host
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: app.wizardry.generated.owl_mobile
      INFOPLIST_KEY_CFBundleDisplayName: "Owl Mobile"
      CURRENT_PROJECT_VERSION: "104521296"
      MARKETING_VERSION: "0.1.0"
